apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angular
          image: yerkebulanratkhan/testassignment:angular
          ports:
            - containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: angular
spec:
  type: NodePort
  selector:
    app: angular
  ports:
    - port: 80
      targetPort: 4200
