apiVersion: apps/v1
kind: Deployment
metadata:
  name: itemsservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itemsservice
  template:
    metadata:
      labels:
        app: itemsservice
    spec:
      containers:
        - name: itemsservice
          image: yerkebulanratkhan/testassignment:itemsservice
          ports:
            - containerPort: 8089

---
apiVersion: v1
kind: Service
metadata:
  name: itemsservice
spec:
  type: NodePort
  selector:
    app: itemsservice
  ports:
    - port: 80
      targetPort: 8089
